Add jumas layout
hammady/wwpray pull request #65
Opened 2023-10-27 10:58 UTC by fayez-nazzal

2023-10-27 10:58 UTC, fayez-nazzal commented
Need to check a real most recent notified.json @hammady

2023-10-27 11:37 UTC, hammady commented
@fayez-nazzal Updated the linked issue.

2023-10-27 11:39 UTC, hammady commented on generator/svelte/src/lib/types.ts
> +	max_jumas: number;
This is now deprecated.

2023-10-27 16:57 UTC, fayez-nazzal commented on generator/svelte/src/lib/types.ts
> +	max_jumas: number;
Removed.

2023-10-28 03:16 UTC, hammady approved these changes

2023-10-28 03:22 UTC, hammady requested changes
Please add the last updated text somewhere below the masjid name.

2023-10-28 08:23 UTC, fayez-nazzal commented
> Please add the last updated text somewhere below the masjid name.

Added.

2023-10-28 14:27 UTC, hammady approved these changes

2023-10-28 16:09 UTC, merged